/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package examples;

/**
 *
 * @author drzam
 */
public class CustomCell extends javax.swing.JPanel {

    /**
     * Creates new form CustomCell
     */
    public CustomCell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelOperation = new javax.swing.JLabel();
        jLabelMesage = new javax.swing.JLabel();
        jLabelEmitId = new javax.swing.JLabel();
        jLabelSpace = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabelOperation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOperation.setText("Data");

        jLabelMesage.setText("wiadomość");

        jLabelEmitId.setText("id");
        jLabelEmitId.setEnabled(false);

        jLabelSpace.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelOperation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmitId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSpace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMesage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelOperation)
                .addComponent(jLabelEmitId)
                .addComponent(jLabelMesage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelSpace))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelEmitId;
    public javax.swing.JLabel jLabelMesage;
    public javax.swing.JLabel jLabelOperation;
    public javax.swing.JLabel jLabelSpace;
    // End of variables declaration//GEN-END:variables
}
